title: Michael Tong
description: 
disqus_shortname: michaeltong
#Your site's domain goes here. Leave localhost server or blank when working locally.
url: http://michael-tong.com
# Owner/author information
owner:
name: Michael Tong
